server:
  port: 8080
  servlet:
    context-path: /outbound

spring:
  application:
    name: OUTBOUND-SERVICE
  profiles:
    active: dev
  messages:
    basename: i18n/message

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.rakuten.ecld.wms.wombatoutbound.entity
  configuration:
    map-underscore-to-camel-case: true

jwt:
  header: Authorization
  secret: express
  expiration: 1800 #seconds
  tokenHeader: "Bearer "

